"""empty message

Revision ID: 1d27d5f9e60e
Revises: 2589d772e15
Create Date: 2015-05-29 02:46:02.833329

"""

# revision identifiers, used by Alembic.
revision = '1d27d5f9e60e'
down_revision = '2589d772e15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoas')
    ### end Alembic commands ###
