"""empty message

Revision ID: 2589d772e15
Revises: 3eb13c64b906
Create Date: 2015-05-29 02:44:26.116682

"""

# revision identifiers, used by Alembic.
revision = '2589d772e15'
down_revision = '3eb13c64b906'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
