"""empty message

Revision ID: 3eb13c64b906
Revises: None
Create Date: 2015-05-29 02:40:02.154845

"""

# revision identifiers, used by Alembic.
revision = '3eb13c64b906'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
